export const settingsChannels = {
  get: 'desktop:get-settings',
  getRuntimeMode: 'desktop:get-runtime-mode',
  getProviderSecret: 'desktop:get-provider-secret',
  saveSettings: 'desktop:save-settings',
  testProviderConnection: 'desktop:test-provider-connection',
  setShortcut: 'desktop:set-shortcut',
  showOverlay: 'desktop:show-overlay',
  showMainWindow: 'desktop:show-main-window',
  hidePopupWindow: 'desktop:hide-popup-window',
  showPopupWindow: 'desktop:show-popup-window',
  getCapabilities: 'desktop:get-capabilities',
  refreshCapabilities: 'desktop:refresh-capabilities',
  openAccessibilitySettings: 'desktop:open-accessibility-settings',
  openScreenRecordingSettings: 'desktop:open-screen-recording-settings',
  showCaptureWindow: 'desktop:show-capture-window',
  submitCaptureSelection: 'desktop:submit-capture-selection',
  cancelCaptureSelection: 'desktop:cancel-capture-selection',
  getLatestCapture: 'desktop:get-latest-capture',
  getPopupState: 'desktop:get-popup-state',
  getWorkspaceDraft: 'desktop:get-workspace-draft',
  promotePopupToWorkspace: 'desktop:promote-popup-to-workspace',
  popupStateUpdated: 'popup:state-updated',
  workspaceDraftUpdated: 'workspace:draft-updated',
  captureCompleted: 'capture:completed',
  captureCancelled: 'capture:cancelled',
  captureWindowClosed: 'capture:window-closed',
} as const;
